### ISSUE TITLE
Linux version is seg faulting

### ISSUE THREAD

**Issue by abhi-bit** [kevinlawler/kerf#2]
```
➜  kerf git:(master) ./KerfREPL/linux/kerf
 ╔═════════════════════════════════════════════════════════════════════════╗
 ║                                                                         ║
 ║                                                                         ║
 ║                                                                         ║
 ║                     ██╗  ██╗ █████╗ ██████╗  ██████╗                    ║
 ║                     ██║ ██╔╝██╔══██╗██╔══██╗███╔═══╝                    ║
 ║                     █████╔╝ ██████╔╝██████╔╝██████╗                     ║
 ║                     ██╔═██╗ ██╔═══╝ ██╔══██╗██╔═══╝                     ║
 ║                     ██║  ██╗╚██████╗██║  ██║██║                         ║
 ║                     ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝     ©                   ║
 ║                                                                         ║
 ║                                                                         ║
 ║                                          {SOLO, 64-BIT, RELEASE, ALPHA} ║
 ╚═════════════════════════════════════════════════════════════════════════╝
Binary expires on 2015.07.26 (1 month from compilation)

[1]    122140 segmentation fault  ./KerfREPL/linux/kerf
➜  kerf git:(master) uname -a
Linux server279 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux
➜  kerf git:(master) lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.3 (wheezy)
Release:        7.3
Codename:       wheezy
➜  kerf git:(master) git rev-parse --verify HEAD
219d5861241963ddad3693bfcc3e11284a726ab1
➜  kerf git:(master)
```

GDB didn't tell me much because debug symbols are missing.

**Comment by kevinlawler** [comment]
via email @abhi-bit reports:
<pre>
<code>
(gdb) bt
#0  0x00007ffff7bb9d09 in ?? () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#1  0x00007ffff7bbaaa5 in terminal_set ()
   from /usr/lib/x86_64-linux-gnu/libedit.so.2
#2  0x00007ffff7bbad6a in terminal_init ()
   from /usr/lib/x86_64-linux-gnu/libedit.so.2
#3  0x00007ffff7bb1b42 in el_init_fd () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#4  0x00007ffff7bb1c45 in el_init () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#5  0x00007ffff7bc1b29 in rl_initialize ()
   from /usr/lib/x86_64-linux-gnu/libedit.so.2
..
</code>
</pre>

which probably indicates libedit incompatibilities. 

I've found this issue in another project: https://github.com/red/red/issues/793#issuecomment-41605000

It would be a disappointment to find that the Linux distros had not found a standardized solution for dealing with libedit. Probably what I will do is creates a build for other Linux platforms that links to `libedit.so.0` instead, and then maybe compile in libedit as a static library or perhaps directly from source so that we can rely on a single binary.

**Comment by kevinlawler** [comment]
This issue should be resolved as of 757483a0cee7f5b3baa31107d2be5328096d815e.

In the meantime I will leave the issue open in case not.

**Comment by kevinlawler** [comment]
I committed a universal linux binary in 7ccc5e045bc562089c9874fc2e7115e3970eac0b
It was compiled to include a static libedit, which should solve these problems.

**Comment by abhi-bit** [comment]
@kevinlawler perfect! 7ccc5e0 works fine.
