### ISSUE TITLE
typos in refmanual.pdf

### ISSUE THREAD

**Issue by hoosierEE** [kevinlawler/kerf#8]
In the code box at the bottom of page 23:

    KeRF> *(3, 5)
      5

And 

    KeRF> +(3, 5)
      5

I suppose these should be 15 and 8, respectively.

**Comment by kevinlawler** [comment]
Good catch. We've fixed this and added additional explanation. It'll go live next time we push the manual.

These expressions actually work as indicated. The problem is in the description: parentheses won't bind as arguments to symbolic operators, so the result of evaluating the parentheses is to return the last item only, which is then operated on by the symbol.

**Comment by hoosierEE** [comment]
Interesting, thanks for clarifying.
